"use client"

import { Groq } from "groq-sdk"

const groq = new Groq({
  apiKey: process.env.NEXT_PUBLIC_GROQ_API_KEY,
  dangerouslyAllowBrowser: true
})

/**
 * Note: High-quality semantic search usually requires vector embeddings 
 * generated by a model like OpenAI's text-embedding-3-small or similar.
 * 
 * Since we are using Groq for inference, we will implement a "Smart Keyword" 
 * expansion logic as a lightweight alternative for semantic search if we don't 
 * have a dedicated embedding API yet.
 */

export async function generateEmbedding(text: string): Promise<number[]> {
  // Placeholder for real embedding generation
  // In a real production app, you'd call OpenAI or a similar service here.
  console.log("Generating embedding for:", text)
  return new Array(1536).fill(0).map(() => Math.random()) 
}

export async function smartSearchExpansion(query: string): Promise<string[]> {
  const prompt = `
    Give me 5-8 related keywords or synonymous concepts for the search query: "${query}".
    Include both technical terms and general concepts.
    Format the response as a simple comma-separated list.
  `

  const chatCompletion = await groq.chat.completions.create({
    messages: [
      {
        role: "system",
        content: "You are a search optimization assistant. Return only keywords."
      },
      {
        role: "user",
        content: prompt
      }
    ],
    model: "llama-3.1-8b-instant"
  })

  const response = chatCompletion.choices[0].message.content || ""
  return response.split(',').map(s => s.trim().toLowerCase())
}
